export const GAME_GAME_SPIN_DELAY = 12000;
export const ROULETTE_REWARD_ANIMATION_DURATION = 4000;
export const ACTIVE_GAME_EXPIRED_DELAY = 3000;
export const ROULETTE_AUTOPLAY_DELAY = 10000;
export const ROULETTE_AUTOPLAY_NOTIFICATION_DELAY = 5000;
export const FIXED_DIGITS = 1;
export const START_BONUS = 20;
export const MIN_AMOUNT_OF_WITHDRAWING = 10;
